name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: node:14-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          REACT_APP_API_URL: https://mordomo-digital-api.herokuapp.com
          REACT_APP_JWT_SECRET: ${{ secrets.REACT_APP_JWT_SECRET }}
          REACT_APP_FIREBASE_APIKEY: ${{ secrets.REACT_APP_FIREBASE_APIKEY }}
          REACT_APP_FIREBASE_AUTHDOMAIN: mordomo-digital.firebaseapp.com
          REACT_APP_FIREBASE_DATABASEURL: https://mordomo-digital.firebaseio.com
          REACT_APP_FIREBASE_PROJECTID: mordomo-digital
          REACT_APP_FIREBASE_STORAGEBUCKET: mordomo-digital.appspot.com
          REACT_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.REACT_APP_FIREBASE_MESSAGINGSENDERID }}
          REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_FIREBASE_APPID }}
          REACT_APP_FIREBASE_MEASUREMENTID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENTID }}
          REACT_APP_OWNERID: ${{ secrets.REACT_APP_OWNERID }}
        run: |
          npm install
          npm run build
      - name: Firebase deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
